version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: TrueLove25320664!
      MYSQL_DATABASE: app_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  app_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "3000:3000"
    volumes:
      - ./client/build:/app/../client/build
      - ./homepage:/app/../homepage
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: TrueLove25320664!
      DB_NAME: app_database
      DB_PORT: 3306
      SERVER_PORT: 3000
    depends_on:
      - mysql
    networks:
      - app_network

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache_wordpress
    ports:
      - "8080:80"
    volumes:
      - ./blog:/var/www/html/blog
      - ./dev-blog:/var/www/html/dev-blog
      - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    networks:
      - app_network

  pixelgrid_server:
    build:
      context: ./pixelgrid/server
      dockerfile: Dockerfile
    container_name: pixelgrid_server
    ports:
      - "4000:5050"
    volumes:
      - ./pixelgrid/client/build:/client/build
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: TrueLove25320664!
      DB_NAME: app_database
      DB_PORT: 3306
      SERVER_PORT: 5050
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
