version: '3.8'

services:
  app_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "3000:3000"
    volumes:
      - ./client/build:/app/../client/build
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app_database
      DB_PORT: 3306
      SERVER_PORT: 3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
